"""migrate to datetime

Revision ID: e1224ed881c8
Revises: 
Create Date: 2023-11-28 20:26:41.706721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1224ed881c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beats', schema=None) as batch_op:
        batch_op.alter_column('date_added',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=True)

    with op.batch_alter_table('layers', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('date_added',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_layers_user_id', 'users', ['user_id'], ['id'])
    with op.batch_alter_table('stems', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('date_added',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_stems_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stems', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date_added',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('layers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date_added',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('beats', schema=None) as batch_op:
        batch_op.alter_column('date_added',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
